### ISSUE TITLE
Proposal to improve readability in preview mode

### ISSUE THREAD

**Issue by LilaRest** [Thiews/Obsidian-Harmonic#4]
Hi !
Here is a proposal to improve readability in preview mode. 
By default the `margin-block-end` and `margin-block-start` values are set to `1em` for elements that are inside each preview section divs.
It conduces to huge line spacing between paragraphs and lists (where list is so far from its previous paragraph) for example, here is a picture :
![harmonic_before](https://user-images.githubusercontent.com/48853371/147369056-9bea1405-3d7e-42df-b6be-95477a9d4b26.png)

So, my proposal is to reduce the `margin-block-end` and `margin-block-start` values to `0.4em` using this CSS rule :
```css
div.workspace-leaf div.markdown-preview-sizer.markdown-preview-section > div > :not(h1, h2, h3, h4, h5, h6) {
    margin-block-start: 0.4em;
    margin-block-end: 0.4em;
}
```
**EDIT : I used the :not() selector to exclude headers of this rule**

And here is the result after this change :
![harmonic_after](https://user-images.githubusercontent.com/48853371/147369078-85e38f6a-d00b-47d0-b419-5f2be95a87f0.png)

I tested this change on my own vault using CSS snippets today and for myself it is really more comfortable to read.

Lilian :slightly_smiling_face:
